export const songs = [
    {
        id: 1,
        title: 'Beneath The Surface',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - Beneath the Surface.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 2,
        title: 'Breaking All Illusions',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - Breaking All Illusions.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 3,
        title: 'Bridges In The Sky',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - Bridges in the Sky.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 4,
        title: 'Build Me Up, Break Me Down',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - Build Me Up, Break Me Down.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 5,
        title: 'Far From Heaven',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - Far from Heaven.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 6,
        title: 'Lost Not Forgotten',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - Lost Not Forgotten.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 7,
        title: 'On The Backs Of Angels',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - On the Backs of Angels.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 8,
        title: 'Outcry',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - Outcry.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 9,
        title: 'This Is The Life',
        audio: '/dt-quiz/assets/audio/A Dramatic Turn of Events - This Is the Life.mp3',
        album: 'A Dramatic Turn of Events',
        image: '/dt-quiz/assets/images/album_covers/adtoe.jpg',
    },
    {
        id: 10,
        title: 'A View From The Top Of The World',
        audio: '/dt-quiz/assets/audio/A View from the Top of the World - A View from the Top of the World.mp3',
        album: 'A View From The Top Of The World',
        image: '/dt-quiz/assets/images/album_covers/avfttotw.jpg',
    },
    {
        id: 11,
        title: 'Answering The Call',
        audio: '/dt-quiz/assets/audio/A View from the Top of the World - Answering the Call.mp3',
        album: 'A View From The Top Of The World',
        image: '/dt-quiz/assets/images/album_covers/avfttotw.jpg',
    },
    {
        id: 12,
        title: 'Awaken The Master',
        audio: '/dt-quiz/assets/audio/A View from the Top of the World - Awaken the Master.mp3',
        album: 'A View From The Top Of The World',
        image: '/dt-quiz/assets/images/album_covers/avfttotw.jpg',
    },
    {
        id: 13,
        title: 'Invisible Monster',
        audio: '/dt-quiz/assets/audio/A View from the Top of the World - Invisible Monster.mp3',
        album: 'A View From The Top Of The World',
        image: '/dt-quiz/assets/images/album_covers/avfttotw.jpg',
    },
    {
        id: 14,
        title: 'Sleeping Giant',
        audio: '/dt-quiz/assets/audio/A View from the Top of the World - Sleeping Giant.mp3',
        album: 'A View From The Top Of The World',
        image: '/dt-quiz/assets/images/album_covers/avfttotw.jpg',
    },
    {
        id: 15,
        title: 'The Alien',
        audio: '/dt-quiz/assets/audio/A View from the Top of the World - The Alien.mp3',
        album: 'A View From The Top Of The World',
        image: '/dt-quiz/assets/images/album_covers/avfttotw.jpg',
    },
    {
        id: 16,
        title: 'Transcending Time',
        audio: '/dt-quiz/assets/audio/A View from the Top of the World - Transcending Time.mp3',
        album: 'A View From The Top Of The World',
        image: '/dt-quiz/assets/images/album_covers/avfttotw.jpg',
    },
    {
        id: 17,
        title: '6:00',
        audio: '/dt-quiz/assets/audio/Awake - 6_00.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 18,
        title: 'Caught In A Web',
        audio: '/dt-quiz/assets/audio/Awake - Caught in a Web.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 19,
        title: 'Erotomania',
        audio: '/dt-quiz/assets/audio/Awake - Erotomania.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 20,
        title: 'Innocence Faded',
        audio: '/dt-quiz/assets/audio/Awake - Innocence Faded.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 21,
        title: 'Lie',
        audio: '/dt-quiz/assets/audio/Awake - Lie.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 22,
        title: 'Lifting Shadows Off A Dream',
        audio: '/dt-quiz/assets/audio/Awake - Lifting Shadows Off a Dream.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 23,
        title: 'Scarred',
        audio: '/dt-quiz/assets/audio/Awake - Scarred.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 24,
        title: 'Space-Dye Vest',
        audio: '/dt-quiz/assets/audio/Awake - Space-Dye Vest.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 25,
        title: 'The Mirror',
        audio: '/dt-quiz/assets/audio/Awake - The Mirror.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 26,
        title: 'The Silent Man',
        audio: '/dt-quiz/assets/audio/Awake - The Silent Man.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 27,
        title: 'Voices',
        audio: '/dt-quiz/assets/audio/Awake - Voices.mp3',
        album: 'Awake',
        image: '/dt-quiz/assets/images/album_covers/awake.jpg',
    },
    {
        id: 28,
        title: 'A Nightmare To Remember',
        audio: '/dt-quiz/assets/audio/Black Clouds & Silver Linings - A Nightmare to Remember.mp3',
        album: 'Black Clouds & Silver Linings',
        image: '/dt-quiz/assets/images/album_covers/bc&sl.jpg',
    },
    {
        id: 29,
        title: 'A Rite Of Passage',
        audio: '/dt-quiz/assets/audio/Black Clouds & Silver Linings - A Rite of Passage.mp3',
        album: 'Black Clouds & Silver Linings',
        image: '/dt-quiz/assets/images/album_covers/bc&sl.jpg',
    },
    {
        id: 30,
        title: 'The Best Of Times',
        audio: '/dt-quiz/assets/audio/Black Clouds & Silver Linings - The Best of Times.mp3',
        album: 'Black Clouds & Silver Linings',
        image: '/dt-quiz/assets/images/album_covers/bc&sl.jpg',
    },
    {
        id: 31,
        title: 'The Count Of Tuscany',
        audio: '/dt-quiz/assets/audio/Black Clouds & Silver Linings - The Count of Tuscany.mp3',
        album: 'Black Clouds & Silver Linings',
        image: '/dt-quiz/assets/images/album_covers/bc&sl.jpg',
    },
    {
        id: 32,
        title: 'The Shattered Fortress',
        audio: '/dt-quiz/assets/audio/Black Clouds & Silver Linings - The Shattered Fortress.mp3',
        album: 'Black Clouds & Silver Linings',
        image: '/dt-quiz/assets/images/album_covers/bc&sl.jpg',
    },
    {
        id: 33,
        title: 'Wither',
        audio: '/dt-quiz/assets/audio/Black Clouds & Silver Linings - Wither.mp3',
        album: 'Black Clouds & Silver Linings',
        image: '/dt-quiz/assets/images/album_covers/bc&sl.jpg',
    },
    {
        id: 34,
        title: `At Wit's End`,
        audio: `/dt-quiz/assets/audio/Distance Over Time - At Wit's End.mp3`,
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 35,
        title: 'Barstool Warrior',
        audio: '/dt-quiz/assets/audio/Distance Over Time - Barstool Warrior.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 36,
        title: 'Fall Into The Light',
        audio: '/dt-quiz/assets/audio/Distance Over Time - Fall into the Light.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 37,
        title: 'Out Of Reach',
        audio: '/dt-quiz/assets/audio/Distance Over Time - Out of Reach.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 38,
        title: 'Pale Blue Dot',
        audio: '/dt-quiz/assets/audio/Distance Over Time - Pale Blue Dot.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 39,
        title: 'Paralyzed',
        audio: '/dt-quiz/assets/audio/Distance Over Time - Paralyzed.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 40,
        title: 'Room 137',
        audio: '/dt-quiz/assets/audio/Distance Over Time - Room 137.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 41,
        title: 'S2N',
        audio: '/dt-quiz/assets/audio/Distance Over Time - S2N.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 42,
        title: 'Untethered Angel',
        audio: '/dt-quiz/assets/audio/Distance Over Time - Untethered Angel.mp3',
        album: 'Distance Over Time',
        image: '/dt-quiz/assets/images/album_covers/dot.jpg',
    },
    {
        id: 43,
        title: 'Along For The Ride',
        audio: '/dt-quiz/assets/audio/Dream Theater - Along for the Ride.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 44,
        title: 'Behind The Veil',
        audio: '/dt-quiz/assets/audio/Dream Theater - Behind the Veil.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 45,
        title: 'Enigma Machine',
        audio: '/dt-quiz/assets/audio/Dream Theater - Enigma Machine.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 46,
        title: 'False Awakening Suite',
        audio: '/dt-quiz/assets/audio/Dream Theater - False Awakening Suite.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 47,
        title: 'Illumination Theory',
        audio: '/dt-quiz/assets/audio/Dream Theater - Illumination Theory.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 48,
        title: 'Surrender To Reason',
        audio: '/dt-quiz/assets/audio/Dream Theater - Surrender to Reason.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 49,
        title: 'The Bigger Picture',
        audio: '/dt-quiz/assets/audio/Dream Theater - The Bigger Picture.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 50,
        title: 'The Enemy Inside',
        audio: '/dt-quiz/assets/audio/Dream Theater - The Enemy Inside.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 51,
        title: 'The Looking Glass',
        audio: '/dt-quiz/assets/audio/Dream Theater - The Looking Glass.mp3',
        album: 'Dream Theater',
        image: '/dt-quiz/assets/images/album_covers/dt.jpg',
    },
    {
        id: 52,
        title: 'Anna Lee',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Anna Lee.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 53,
        title: 'Burning My Soul',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Burning My Soul.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 54,
        title: `Hell's Kitchen`,
        audio: `/dt-quiz/assets/audio/Falling into Infinity - Hell's Kitchen.mp3`,
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 55,
        title: 'Hollow Years',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Hollow Years.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 56,
        title: 'Just Let Me Breathe',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Just Let Me Breathe.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 57,
        title: 'Lines In The Sand',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Lines in the Sand.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 58,
        title: 'New Millennium',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - New Millennium.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 59,
        title: 'Peruvian Skies',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Peruvian Skies.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 60,
        title: 'Take Away My Pain',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Take Away My Pain.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 61,
        title: 'Trial Of Tears',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - Trial of Tears.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 62,
        title: 'You Not Me',
        audio: '/dt-quiz/assets/audio/Falling into Infinity - You Not Me.mp3',
        album: 'Falling Into Infinity',
        image: '/dt-quiz/assets/images/album_covers/fii.jpg',
    },
    {
        id: 63,
        title: 'Another Day',
        audio: '/dt-quiz/assets/audio/Images and Words - Another Day.mp3',
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 64,
        title: 'Learning To Live',
        audio: '/dt-quiz/assets/audio/Images and Words - Learning to Live.mp3',
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 65,
        title: 'Metropolis - Part I: "The Miracle And The Sleeper"',
        audio: `/dt-quiz/assets/audio/Images and Words - Metropolis Part I 'The Miracle and the Sleeper'.mp3`,
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 66,
        title: 'Pull Me Under',
        audio: '/dt-quiz/assets/audio/Images and Words - Pull Me Under.mp3',
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 67,
        title: 'Surrounded',
        audio: '/dt-quiz/assets/audio/Images and Words - Surrounded.mp3',
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 68,
        title: 'Take The Time',
        audio: '/dt-quiz/assets/audio/Images and Words - Take the Time.mp3',
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 69,
        title: 'Under A Glass Moon',
        audio: '/dt-quiz/assets/audio/Images and Words - Under a Glass Moon.mp3',
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 70,
        title: 'Wait For Sleep',
        audio: '/dt-quiz/assets/audio/Images and Words - Wait for Sleep.mp3',
        album: 'Images and Words',
        image: '/dt-quiz/assets/images/album_covers/i&w.jpg',
    },
    {
        id: 71,
        title: 'I Walk Beside You',
        audio: '/dt-quiz/assets/audio/Octavarium - I Walk Beside You.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 72,
        title: 'Never Enough',
        audio: '/dt-quiz/assets/audio/Octavarium - Never Enough.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 73,
        title: 'Octavarium',
        audio: '/dt-quiz/assets/audio/Octavarium - Octavarium.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 74,
        title: 'Panic Attack',
        audio: '/dt-quiz/assets/audio/Octavarium - Panic Attack.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 75,
        title: 'Sacrificed Sons',
        audio: '/dt-quiz/assets/audio/Octavarium - Sacrificed Sons.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 76,
        title: 'The Answer Lies Within',
        audio: '/dt-quiz/assets/audio/Octavarium - The Answer Lies Within.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 77,
        title: 'The Root Of All Evil',
        audio: '/dt-quiz/assets/audio/Octavarium - The Root of All Evil.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 78,
        title: 'These Walls',
        audio: '/dt-quiz/assets/audio/Octavarium - These Walls.mp3',
        album: 'Octavarium',
        image: '/dt-quiz/assets/images/album_covers/octavarium.jpg',
    },
    {
        id: 79,
        title: 'Beyond This Life',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Beyond This Life.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 80,
        title: 'Fatal Tragedy',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Fatal Tragedy.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 81,
        title: 'Finally Free',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Finally Free.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 82,
        title: 'Home',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Home.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 83,
        title: 'One Last Time',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - One Last Time.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 84,
        title: 'Overture 1928',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Overture 1928.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 85,
        title: 'Regression',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Regression.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 86,
        title: 'Strange Deja Vu',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Strange Deja Vu.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 87,
        title: 'The Dance Of Eternity',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - The Dance of Eternity.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 88,
        title: 'The Spirit Carries On',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - The Spirit Carries On.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 89,
        title: 'Through Her Eyes',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Through Her Eyes.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 90,
        title: 'Through My Words',
        audio: '/dt-quiz/assets/audio/Scenes from a Memory - Through My Words.mp3',
        album: 'Scenes From A Memory',
        image: '/dt-quiz/assets/images/album_covers/sfam.jpg',
    },
    {
        id: 91,
        title: 'Blind Faith',
        audio: '/dt-quiz/assets/audio/Six Degrees of Inner Turbulence - Blind Faith.mp3',
        album: 'Six Degrees Of Inner Turbulence',
        image: '/dt-quiz/assets/images/album_covers/sdoit.jpg',
    },
    {
        id: 92,
        title: 'Disappear',
        audio: '/dt-quiz/assets/audio/Six Degrees of Inner Turbulence - Disappear.mp3',
        album: 'Six Degrees Of Inner Turbulence',
        image: '/dt-quiz/assets/images/album_covers/sdoit.jpg',
    },
    {
        id: 93,
        title: 'Misunderstood',
        audio: '/dt-quiz/assets/audio/Six Degrees of Inner Turbulence - Misunderstood.mp3',
        album: 'Six Degrees Of Inner Turbulence',
        image: '/dt-quiz/assets/images/album_covers/sdoit.jpg',
    },
    {
        id: 94,
        title: 'Six Degrees Of Inner Turbulence',
        audio: '/dt-quiz/assets/audio/Six Degrees of Inner Turbulence - Six Degrees of Inner Turbulence.mp3',
        album: 'Six Degrees Of Inner Turbulence',
        image: '/dt-quiz/assets/images/album_covers/sdoit.jpg',
    },
    {
        id: 95,
        title: 'The Glass Prison',
        audio: '/dt-quiz/assets/audio/Six Degrees of Inner Turbulence - The Glass Prison.mp3',
        album: 'Six Degrees Of Inner Turbulence',
        image: '/dt-quiz/assets/images/album_covers/sdoit.jpg',
    },
    {
        id: 96,
        title: 'The Great Debate',
        audio: '/dt-quiz/assets/audio/Six Degrees of Inner Turbulence - The Great Debate.mp3',
        album: 'Six Degrees Of Inner Turbulence',
        image: '/dt-quiz/assets/images/album_covers/sdoit.jpg',
    },
    {
        id: 97,
        title: 'Constant Motion',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - Constant Motion.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 98,
        title: 'Forsaken',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - Forsaken.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 99,
        title: 'In The Presence Of Enemies - Part I',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - In the Presence of Enemies - Part I.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 100,
        title: 'In The Presence Of Enemies - Part II',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - In the Presence of Enemies - Part II.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 101,
        title: 'Prophets Of War',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - Prophets of War.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 102,
        title: 'Repentance',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - Repentance.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 103,
        title: 'The Dark Eternal Night',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - The Dark Eternal Night.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 104,
        title: 'The Ministry Of Lost Souls',
        audio: '/dt-quiz/assets/audio/Systematic Chaos - The Ministry of Lost Souls.mp3',
        album: 'Systematic Chaos',
        image: '/dt-quiz/assets/images/album_covers/sc.jpg',
    },
    {
        id: 105,
        title: 'A Life Left Behind',
        audio: '/dt-quiz/assets/audio/The Astonishing - A Life Left Behind.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 106,
        title: 'A New Beginning',
        audio: '/dt-quiz/assets/audio/The Astonishing - A New Beginning.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 107,
        title: 'Dystopian Overture',
        audio: '/dt-quiz/assets/audio/The Astonishing - Dystopian Overture.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 108,
        title: 'Moment Of Betrayal',
        audio: '/dt-quiz/assets/audio/The Astonishing - Moment of Betrayal.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 109,
        title: 'My Last Farewell',
        audio: '/dt-quiz/assets/audio/The Astonishing - My Last Farewell.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 110,
        title: 'Our New World',
        audio: '/dt-quiz/assets/audio/The Astonishing - Our New World.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 111,
        title: 'The Answer',
        audio: '/dt-quiz/assets/audio/The Astonishing - The Answer.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 112,
        title: 'The Gift Of Music',
        audio: '/dt-quiz/assets/audio/The Astonishing - The Gift of Music.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 113,
        title: 'The Path That Divides',
        audio: '/dt-quiz/assets/audio/The Astonishing - The Path That Divides.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 114,
        title: 'The Walking Shadow',
        audio: '/dt-quiz/assets/audio/The Astonishing - The Walking Shadow.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 115,
        title: 'Three Days',
        audio: '/dt-quiz/assets/audio/The Astonishing - Three Days.mp3',
        album: 'The Astonishing',
        image: '/dt-quiz/assets/images/album_covers/astonishing.jpg',
    },
    {
        id: 116,
        title: 'As I Am',
        audio: '/dt-quiz/assets/audio/Train of Thought - As I Am.mp3',
        album: 'Train Of Thought',
        image: '/dt-quiz/assets/images/album_covers/tot.jpg',
    },
    {
        id: 117,
        title: 'Endless Sacrifice',
        audio: '/dt-quiz/assets/audio/Train of Thought - Endless Sacrifice.mp3',
        album: 'Train Of Thought',
        image: '/dt-quiz/assets/images/album_covers/tot.jpg',
    },
    {
        id: 118,
        title: 'Honor Thy Father',
        audio: '/dt-quiz/assets/audio/Train of Thought - Honor Thy Father.mp3',
        album: 'Train Of Thought',
        image: '/dt-quiz/assets/images/album_covers/tot.jpg',
    },
    {
        id: 119,
        title: 'In The Name Of God',
        audio: '/dt-quiz/assets/audio/Train of Thought - In the Name of God.mp3',
        album: 'Train Of Thought',
        image: '/dt-quiz/assets/images/album_covers/tot.jpg',
    },
    {
        id: 120,
        title: 'Stream Of Consciousness',
        audio: '/dt-quiz/assets/audio/Train of Thought - Stream of Consciousness.mp3',
        album: 'Train Of Thought',
        image: '/dt-quiz/assets/images/album_covers/tot.jpg',
    },
    {
        id: 121,
        title: 'This Dying Soul',
        audio: '/dt-quiz/assets/audio/Train of Thought - This Dying Soul.mp3',
        album: 'Train Of Thought',
        image: '/dt-quiz/assets/images/album_covers/tot.jpg',
    },
    {
        id: 122,
        title: 'Vacant',
        audio: '/dt-quiz/assets/audio/Train of Thought - Vacant.mp3',
        album: 'Train Of Thought',
        image: '/dt-quiz/assets/images/album_covers/tot.jpg',
    },
    {
        id: 123,
        title: 'A Fortune In Lies',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - A Fortune in Lies.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
    {
        id: 124,
        title: 'Afterlife',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - Afterlife.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
    {
        id: 125,
        title: 'Light Fuse And Get Away',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - Light Fuse and Get Away.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
    {
        id: 126,
        title: 'Only A Matter Of Time',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - Only a Matter of Time.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
    {
        id: 127,
        title: 'Status Seeker',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - Status Seeker.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
    {
        id: 128,
        title: 'The Killing Hand',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - The Killing Hand.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
    {
        id: 129,
        title: 'The Ones Who Help To Set The Sun',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - The Ones Who Help to Set the Sun.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
    {
        id: 130,
        title: 'The Ytse Jam',
        audio: '/dt-quiz/assets/audio/When Dream and Day Unite - The Ytse Jam.mp3',
        album: 'When Dream And Day Unite',
        image: '/dt-quiz/assets/images/album_covers/wdadu.jpg',
    },
] 